### ISSUE TITLE
「僅」獻給，是否應該是「謹」獻給⋯⋯但如果原意是「只有」，好像也可以用「僅」。🐕

### ISSUE THREAD

**Issue by leechiuhui** [bestian/rpg#1]

**Comment by leechiuhui** [comment]
![image](https://github.com/bestian/rpg/assets/107933615/e8944d89-6e45-4204-ad51-14458ce06b99)

**Comment by bestian** [comment]
@leechiuhui 我直接開權限給你好了。校對真的不是我一人之力所能及的。

https://github.com/bestian/stars-new/issues/12

**Comment by bestian** [comment]
well done
